### ISSUE TITLE
Please add some text documents to your repository

### ISSUE THREAD

**Issue by KevinBretonnelCohen** [UCDenver-ccp/Knowtator-2.0#2]
Please consider adding some text documents to your repository/distribution--for example, perhaps the one(s) in your illustrations in the README?

**Comment by tuh8888** [comment]
There is one and it's annotation xml already located at Knowtator-2.0/src/main/resources/file/ which is included in the JAR file. It is the one from the illustrations in the README and should be loaded automatically when starting a new session.

**Comment by KevinBretonnelCohen** [comment]
Consider documenting that someplace obvious to the new user.

**Comment by tuh8888** [comment]
I have now included their location in the README. For now, they should be loaded automatically upon setup to function as a sort of initial tutoral.
