### ISSUE TITLE
Directory not created on installation

### ISSUE THREAD

**Issue by KevinBretonnelCohen** [UCDenver-ccp/Knowtator-2.0#3]
The directory that's referred to here:

> Copy Knowtator-2.0.jar to Protege.X.X/plugins/

...wasn't created when I installed Protege.

**Comment by tuh8888** [comment]
Hmm... that directory is created when I installed Protege 5.2.0 Desktop for windows. On a Mac, where would you install plugins for Protege to?

**Comment by KevinBretonnelCohen** [comment]
I don't know where they currently think they're going.  Want to look at it on my machine?  Email me.

**Comment by tuh8888** [comment]
See the Mac installation section in the README.md
