### ISSUE TITLE
Create a release on github

### ISSUE THREAD

**Issue by csnyulas** [UCDenver-ccp/Knowtator-2.0#8]
It would be nice if you would create a github release ([here](https://github.com/UCDenver-ccp/Knowtator-2.0/releases)), where people could download the jar file, instead of keeping it together with the source code, and expecting people to find it.

**Comment by tuh8888** [comment]
I didn't actually know that was a place to put things. Thanks! I will do that for the next release

**Comment by csnyulas** [comment]
Cool!
Also, it is a bit confusing that there are two public repositories for Knowtator 2.0. This being the other one: https://github.com/tuh8888/Knowtator-2.0 A , which is higher ranked in the Google search results than this one.
As a casual user, looking for a text annotator plug-in for Protege, I am not sure which one to use, or may not even be aware of the second one, so I may not use the recommended one.

**Comment by tuh8888** [comment]
You're right that is confusing. I will remove my fork
